name: update-sitemap

on:
  schedule:
    - cron:  '10 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Get New ranking.xml
      run: |
        curl "https://storage.googleapis.com/vtuber.ytubelab.com/sitemap/ranking.xml?_=`date +%s`" -o ./static/sitemap/ranking.xml
    - name: Get New watch.xml
      run: |
        curl "https://storage.googleapis.com/vtuber.ytubelab.com/sitemap/watch.xml?_=`date +%s`" -o ./static/sitemap/watch.xml
    - name: Get New channel.xml
      run: |
        curl "https://storage.googleapis.com/vtuber.ytubelab.com/sitemap/channel.xml?_=`date +%s`" -o ./static/sitemap/channel.xml
    - name: Get New user[1-100].xml
      run: |
        curl -f "https://storage.googleapis.com/vtuber.ytubelab.com/sitemap/user[1-100].xml?_=`date +%s`" -o ./static/sitemap/user#1.xml
      continue-on-error: true
    - name: update sitemap.xml
      run: |
        xml="<?xml version=\"1.0\" encoding=\"UTF-8\"?><sitemapindex xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">"
        for entry in "static/sitemap"/*
        do
          xml="$xml<sitemap><loc>https://vtuber.ytubelab.com/sitemap/`basename $entry`</loc><lastmod>`date -I`</lastmod></sitemap>"
        done
        xml="$xml</sitemapindex>"
        echo "$xml" > static/sitemap.xml
    - name: git setting
      run: |
        git config --local user.email "yoshiaki@natsu.me"
        git config --local user.name "GitHub Actions"
    - name: Commit files
      run: |
        git add ./static/sitemap/
        git add ./static/sitemap.xml
        git commit -m "update sitemap.xml by GitHub Actions" ./static/sitemap/ ./static/sitemap.xml
        git pull
        git push origin master
